// ============================================================================
// Pixel Folder — Selena Zeng's portfolio content.
// ============================================================================

const asset = (path) => `${import.meta.env.BASE_URL}${path.replace(/^\/+/, "")}`;

export const content = {
  hero: {
    brand: "Selena Zeng",
    stamp: "CONSUMER STRATEGY × PRODUCT × GROWTH",
    name: "Selena Zeng",
    introLine1: "I translate consumer behavior into growth and product decisions",
    introLine2: "by combining consumer insight, product thinking, lifecycle strategy, and analytics.",
    location: "Los Angeles / Beijing",
    availability: "Graduating December 2026 · Open to full-time roles",
  },

  marquee: [
    "Consumer Strategy",
    "Product Thinking",
    "Lifecycle Growth",
    "Analytics",
    "Consumer Insight",
    "Growth Strategy",
  ],

  workSection: {
    eyebrow: "HOME / SELECTED WORK",
    title: "Work across product, growth, and consumer strategy",
    description: "Selected projects spanning lifecycle growth, product thinking, analytics, and consumer insight.",
  },

  projects: [
    {
      title: "Lifecycle Marketing & CRM Campaigns",
      description: "Configured and operated 3-, 5-, and 10-drink prepaid passes designed to encourage repeat purchases and retention.",
      image: "",
      category: "Lifecycle Marketing",
      tags: ["Customer Segmentation", "Product Operations"],
      year: "2026",
      link: "",
      detail: "Supported pass setup, behavioral segmentation, tiered refund rules, customer outreach, participating-store scope, and launch operations.",
      folderIcon: asset("/folder-icons/red-rabbit-folder.png"),
      caseStudy: {
        type: "lifecycle",
        fileNumber: "01",
        eyebrow: "LUCKIN COFFEE / LIFECYCLE GROWTH",
        title: "Tiered-Pricing Prepaid Drink Pass Strategy",
        subtitle: "A lifecycle growth program that paired 3-, 5-, and 10-drink prepaid passes with behavioral segmentation and tiered refund logic to encourage repeat purchases and pass completion.",
        snapshot: [
          { value: "03", label: "Pass variants" },
          { value: "02", label: "Program mechanics" },
          { value: "03", label: "Customer segments" },
          { value: "CRM", label: "Lifecycle operations" },
        ],
        contextTitle: "Match commitment level to customer behavior",
        overview: "Customers had different purchase-frequency patterns and different willingness to commit upfront. The program offered 3-, 5-, and 10-drink prepaid passes: smaller passes lowered the barrier to entry, while larger passes better matched customers with higher existing purchase frequency. The goal was to support repeat purchases and encourage customers to complete the pass.",
        role: [
          "Configured multiple prepaid pass variants and supporting product setups",
          "Maintained SKU and voucher mappings",
          "Translated behavioral segments into campaign eligibility rules",
          "Coordinated outreach strategy, product scope, and participating stores",
          "Configured tiered refund logic and supporting business rules",
          "Supported launch readiness and ongoing campaign operations",
        ],
        goals: [
          { title: "Beverage volume", text: "Encourage more drink purchases through continued pass redemption." },
          { title: "Purchase frequency", text: "Give customers a reason to return for their remaining drinks." },
          { title: "Retention", text: "Encourage customers to return while they have drinks left to redeem." },
          { title: "Upfront commitment", text: "Create upfront commitment to future drink purchases." },
        ],
        passVariants: [
          { value: "03", label: "Lower barrier to entry", accent: "pink" },
          { value: "05", label: "Mid-level commitment", accent: "yellow" },
          { value: "10", label: "Better fit for higher-frequency customers", accent: "green" },
        ],
        segments: [
          { tier: "LOWER FREQUENCY", recommendation: "Smaller pass", text: "Lower the upfront commitment for customers with less-established purchase behavior." },
          { tier: "MID FREQUENCY", recommendation: "Medium pass", text: "Match customers who already buy repeatedly and may increase purchase frequency." },
          { tier: "HIGHER FREQUENCY", recommendation: "Larger pass", text: "Offer greater value and a better fit for higher existing purchase frequency." },
        ],
        mechanisms: [
          {
            number: "01",
            title: "Prepaid commitment",
            text: "Customers pay upfront, committing to future drink purchases.",
          },
          {
            number: "02",
            title: "Tiered refund logic",
            text: "If a customer exits the pass early, completed redemptions are repriced based on the applicable usage tier. This makes completing the pass more economically attractive while preserving the option to exit early.",
          },
        ],
        behavioralInsights: [
          { title: "Sunk cost effect", text: "After redeeming part of a prepaid pass, customers may be more motivated to use the remaining drinks rather than leave the pass unfinished." },
          { title: "Commitment mechanism", text: "An upfront choice turns future visits into a plan rather than a new decision each time." },
        ],
        outcome: "The program connected customer segmentation with prepaid pass setup, lifecycle outreach, and tiered refund rules. My work supported the product configuration and campaign operations used to match different pass sizes to different customer behaviors.",
      },
    },
    {
      title: "Campaign Planning & Launch Operations",
      description: "Turned seasonal campaign ideas into coordinated in-app launches across offers, products, creative assets, and QA.",
      image: asset("/works/activity-planning/campaign-popup.jpg"),
      category: "Campaign Operations",
      tags: ["Launch Planning", "Cross-functional Ops"],
      year: "2026",
      link: "",
      detail: "Translated campaign ideas into launch requirements, coordinated cross-functional handoffs, and checked the full customer journey before release.",
      folderIcon: asset("/folder-icons/blue-folder.png"),
      caseStudy: {
        type: "campaign",
        fileNumber: "02",
        eyebrow: "LUCKIN COFFEE / CAMPAIGN OPERATIONS",
        title: "Campaign Planning & Launch Operations",
        subtitle: "I helped turn seasonal campaign ideas into working in-app experiences by aligning offer rules, product setup, creative assets, placement, and launch QA.",
        snapshot: [
          { value: "03", label: "Campaign formats" },
          { value: "05", label: "Launch stages" },
          { value: "04", label: "Functions aligned" },
          { value: "E2E", label: "Customer journey QA" },
        ],
        contextTitle: "The challenge was coordination, not just creative",
        overview: "A seasonal campaign could look simple to customers, but its launch depended on offer rules, product selection, price display, copy, creative assets, and app placement being ready at the same time. I turned the campaign concept into a practical launch plan and kept those pieces aligned through release.",
        role: [
          "Broke campaign concepts into offer, product, placement, timing, and asset requirements",
          "Coordinated handoffs across marketing, product, design, and operations",
          "Prepared customer-facing copy and campaign materials",
          "Checked the full app journey before launch and followed up on issues",
        ],
        workflow: [
          { step: "01", title: "Define", text: "Start with the campaign goal, target experience, products, and launch window." },
          { step: "02", title: "Build", text: "Translate the idea into offer rules, product combinations, and price presentation." },
          { step: "03", title: "Align", text: "Coordinate copy, creative assets, app placements, and team handoffs." },
          { step: "04", title: "Check", text: "Walk through the customer journey and resolve mismatches before release." },
          { step: "05", title: "Launch", text: "Publish the campaign and confirm that the live experience works as intended." },
        ],
        examples: [
          {
            image: asset("/works/activity-planning/campaign-popup.jpg"),
            alt: "Public Luckin Coffee app popup for a seasonal frozen-drink campaign",
            title: "Campaign entry point",
            text: "The popup introduced the seasonal offer before customers entered the product journey.",
          },
          {
            image: asset("/works/activity-planning/bilingual-app-examples.jpg"),
            alt: "Luckin Coffee app product and menu screens showing the seasonal promotion",
            title: "Product journey",
            text: "The menu and product pages carried the campaign from initial interest to product selection.",
          },
        ],
        launchChecks: [
          "The offer rules, eligible products, and price display told the same story",
          "Creative assets appeared in the right placements and at the right time",
          "Copy stayed consistent from the campaign entry point to product selection",
          "The live journey worked end to end before customers saw it",
        ],
        outcome: "The campaign reached customers as one coherent experience rather than a collection of disconnected assets. My work connected the original idea with the operational details that made the launch usable and consistent in the app.",
      },
    },
    {
      title: "Weekly New Product Pre-sale Workflow",
      description: "Ran a repeatable two-week workflow for new-product pre-sales, from setup and launch checks to reporting and the next release.",
      image: asset("/works/presale-workflow/preorder-app-example.png"),
      category: "Launch Operations",
      tags: ["SOP Design", "Weekly Operations"],
      year: "2026",
      link: "",
      detail: "Kept voucher-to-listing mapping, creative requests, approvals, launch checks, and reporting moving on one weekly schedule, then documented the process for reuse.",
      folderIcon: asset("/folder-icons/green-folder.png"),
      caseStudy: {
        type: "presale",
        fileNumber: "03",
        eyebrow: "LUCKIN COFFEE / WEEKLY LAUNCH OPERATIONS",
        title: "Weekly New Product Pre-sale Workflow",
        subtitle: "I ran a repeatable two-week cycle that connected product setup, creative coordination, approvals, launch checks, and post-launch reporting.",
        snapshot: [
          { value: "02", label: "Week cycle" },
          { value: "03", label: "Launch phases" },
          { value: "04", label: "Reporting steps" },
          { value: "01", label: "Reusable SOP" },
        ],
        contextTitle: "The real challenge was keeping a weekly launch on track",
        overview: "Every new-product pre-sale had the same deadline but many moving parts: product information, Mini Program placement, creative requests, voucher-to-listing mapping, approvals, final assets, launch checks, and reporting. I kept those dependencies on one schedule and used the following week's data to begin the next cycle.",
        role: [
          "Managed the weekly checklist from product setup through reporting",
          "Mapped coffee vouchers to digital product listings and configured optional size-upgrade vouchers",
          "Coordinated copy, images, placements, approvals, and launch checks",
          "Turned the recurring process into an SOP that future interns could follow",
        ],
        weekOne: [
          {
            phase: "MON–TUE",
            accent: "blue",
            title: "Prepare & Configure",
            steps: [
              "Update new product information",
              "Schedule Mini Program placements and submit creative requests",
              "Map the coffee voucher to its digital product listing",
              "Submit materials for review and approval",
            ],
          },
          {
            phase: "THU–FRI",
            accent: "yellow",
            title: "Approve & Publish",
            steps: [
              "Complete required approvals",
              "Update voucher and product images with final assets",
              "Publish the product listing",
              "Configure a size-upgrade voucher when needed",
            ],
          },
          {
            phase: "WEEKEND",
            accent: "pink",
            title: "Verify Release",
            steps: [
              "Confirm products are ready for launch",
              "Verify the customer-facing placement after launch",
              "Document the live placement for post-launch tracking",
            ],
          },
        ],
        weekTwo: [
          { step: "01", title: "Track redemption", text: "Review how the previous release's vouchers were redeemed." },
          { step: "02", title: "Track sales", text: "Check pre-sale voucher sales for the latest release." },
          { step: "03", title: "Review performance", text: "Compare the two signals and flag anything that needs follow-up." },
          { step: "04", title: "Start the next cycle", text: "Carry the findings into the next product launch plan." },
        ],
        sopBenefits: [
          "Put recurring tasks, deadlines, and handoffs in one place",
          "Made launch status easier to follow across product, creative, and operations",
          "Gave future interns a checklist they could use with less day-to-day guidance",
        ],
        appExample: {
          image: asset("/works/presale-workflow/preorder-app-example.png"),
          alt: "Public Luckin Coffee Mini Program screen showing an early-bird pre-sale category and new products",
          title: "Customer-facing release",
          text: "The Mini Program shows where the weekly setup appeared after launch.",
        },
        outcome: "The process became easier to run, review, and hand off. The SOP gave future interns a practical starting point, reduced repeated explanations from mentors, and helped the team keep weekly launches consistent.",
      },
    },
    {
      title: "Customer Feedback Survey & NPS Analysis",
      description: "Built three audience-specific surveys and turned validated customer feedback into product and lifecycle priorities.",
      image: "",
      category: "Voice of Customer",
      tags: ["Survey Operations", "NPS Analysis"],
      year: "2026",
      link: "",
      detail: "Translated business questions into targeted surveys, coordinated outreach, cleaned thousands of responses, and synthesized NPS, satisfaction, and open-text feedback for product and lifecycle teams.",
      folderIcon: asset("/folder-icons/green-folder.png"),
      caseStudy: {
        type: "survey",
        fileNumber: "04",
        eyebrow: "LUCKIN COFFEE / VOICE OF CUSTOMER",
        title: "Customer Feedback Survey & NPS Analysis",
        subtitle: "I built three audience-specific surveys, cleaned thousands of responses, and turned NPS, satisfaction, and open-text feedback into priorities for product and lifecycle teams.",
        snapshot: [
          { value: "03", label: "Customer groups" },
          { value: "1,000s", label: "Responses cleaned" },
          { value: "04", label: "Validation checks" },
          { value: "E2E", label: "Research workflow" },
        ],
        contextTitle: "Different customer behaviors called for different questions",
        overview: "The team did not need another generic satisfaction survey. It needed to understand why some customers stopped buying, what brought others back, and where high-intent customers encountered friction before ordering. I turned those business questions into three targeted surveys and built the workflow from outreach through analysis.",
        role: [
          "Turned business questions into a research plan for three customer groups",
          "Designed the questionnaires and coordinated targeted outreach and incentives",
          "Built a repeatable process for cleaning responses and analyzing NPS",
          "Combined survey scores and open-text feedback into clear recommendations",
        ],
        workflow: [
          { step: "01", title: "Define", text: "Clarify the decision the team needed to make and who could answer it." },
          { step: "02", title: "Design", text: "Build questions around each group's behavior and customer journey." },
          { step: "03", title: "Launch", text: "Coordinate targeting, outreach, and survey incentives." },
          { step: "04", title: "Clean", text: "Remove low-quality, duplicate, and ineligible responses." },
          { step: "05", title: "Interpret", text: "Connect NPS, satisfaction, and comments to product and lifecycle actions." },
        ],
        cohorts: [
          { name: "Inactive customers", goal: "What made them stop, and what needs were no longer being met?", accent: "pink" },
          { name: "Reactivated customers", goal: "What brought them back after a period of inactivity?", accent: "yellow" },
          { name: "High-intent non-purchasers", goal: "Where did interest fail to become an order?", accent: "green" },
        ],
        qualityChecks: [
          { name: "Completion time", note: "Flagged submissions that were unusually fast or slow" },
          { name: "Answer patterns", note: "Checked repetitive and low-variance responses" },
          { name: "Duplicate signals", note: "Reviewed repeated identifiers and network-level signals" },
          { name: "Audience match", note: "Confirmed that responses came from the intended group" },
        ],
        experienceDimensions: [
          "Product experience",
          "Value perception",
          "Ordering journey",
          "Store & fulfillment",
          "Brand & packaging",
        ],
        npsGroups: [
          { label: "Detractors", score: "0–6", width: 50, color: "pink" },
          { label: "Passives", score: "7–8", width: 22, color: "yellow" },
          { label: "Promoters", score: "9–10", width: 28, color: "green" },
        ],
        insightTiers: [
          { label: "Price & value", tier: "HIGH SIGNAL", width: 96 },
          { label: "Convenience", tier: "HIGH SIGNAL", width: 88 },
          { label: "Product experience", tier: "HIGH SIGNAL", width: 82 },
          { label: "Fulfillment", tier: "MID SIGNAL", width: 58 },
          { label: "Brand & service", tier: "EMERGING", width: 30 },
        ],
        insights: [
          "Each customer group needed its own survey logic; one generic questionnaire would have hidden the reason behind the behavior.",
          "NPS showed the strength of recommendation, while experience questions and comments helped explain why customers felt that way.",
          "A reusable cleaning and analysis process made the findings easier to trust and future survey waves easier to run.",
        ],
        outcome: "The project gave product, UX, and lifecycle teams a shared view of where customers were struggling and what to prioritize next. It also created a repeatable research process that could be reused for future survey waves.",
      },
    },
  ],

  aboutSection: {
    eyebrow: "ABOUT / EXPERIENCE",
    title: "The person behind the numbers",
  },

  about: {
    name: "Selena Zeng",
    profileName: "Selena Zeng",
    profileImage: asset("/about/profile.jpg"),
    profileAlt: "Portrait of Selena Zeng holding white tulips outdoors",
    postcardImage: asset("/about/stamp-paper.jpg"),
    greeting: "Hello, I'm Selena.",
    body: "I’m currently studying Economics and Data Science at the University of Southern California and expect to graduate in December 2026. Before USC, I studied Finance and Accounting at the University of Pittsburgh from 2022 to 2024. I’m curious about why users do what they do, how they lose interest, and how better segmentation, communication, and experiences turn casual users into loyal ones. My background combines user growth, business analytics, and consulting. My personal interests include photography, hiking, fashion, skiing, Pilates, and live concerts. In my free time, I also run two RedNote accounts that have earned over 7,000 likes.",
  },

  skills: ["User Growth", "CRM & Lifecycle Marketing", "Customer Research", "SQL / Power BI", "Data Storytelling"],

  experiences: [
    {
      year: "2026",
      role: "User Growth Operations Intern",
      period: "Internship · Present",
      company: "Luckin Coffee · Beijing",
      meta: "Luckin Coffee · Beijing, China",
      description: "Execute CRM and lifecycle campaigns, conduct customer research with 100+ users, manage feedback operations, and coordinate weekly launches across marketing, product, design, and operations.",
      desc: "Execute CRM and lifecycle campaigns, conduct customer research, manage feedback operations, and coordinate weekly launches across marketing, product, design, and operations.",
      tags: ["CRM", "Research", "Launch Ops"],
      visual: "CRM",
    },
    {
      year: "2024",
      role: "Consulting Intern — Government & Public Services",
      period: "Internship · Winter",
      company: "Deloitte · Beijing",
      meta: "Deloitte · Beijing, China",
      description: "Synthesized 15+ expert and partner reports into executive briefs, reducing senior stakeholder review time by approximately 35% and helping multiple teams align on trends and risks.",
      desc: "Synthesized 15+ expert and partner reports into executive briefs, reducing senior stakeholder review time by approximately 35%.",
      tags: ["Consulting", "Synthesis"],
      visual: "CONS",
    },
    {
      year: "2024",
      role: "Business Analyst Intern",
      period: "Internship · Summer",
      company: "Xylem Inc. · Pittsburgh",
      meta: "Xylem Inc. · Pittsburgh, PA",
      description: "Analyzed a $15M customer portfolio in Power BI to improve sales efficiency by 10%, and used Excel and SAP analysis to help reduce excess inventory by 30%.",
      desc: "Analyzed a $15M customer portfolio in Power BI to improve sales efficiency by 10%, and supported inventory analysis in Excel and SAP.",
      tags: ["Power BI", "Excel", "SAP"],
      visual: "BI",
    },
  ],

  contact: {
    titleLine1: "Let's",
    titleLine2: "connect",
    lead: "I am seeking full-time opportunities in consumer strategy, product strategy, growth, or analytics after graduating in December 2026.",
    linkedinHref: "https://www.linkedin.com/in/selenazeng912",
    linkedinText: "View my profile",
    emailHref: "mailto:yue.zeng@outlook.com",
    emailText: "yue.zeng@outlook.com",
  },
};
